version: '2.1'
services:
  mongo:
    image: mongo:3.6.4
    ports:
      - 27017:27017
    command: --smallfiles

  mongo-express:
    image: library/mongo-express:latest
    ports:
      - 9090:8081

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1